# Aula 2 - Python e Numpy

### Erros de Sintaxe

#### Sintaxe é um conjunto de regras que definem o que são ou não sentenças válidas.
#### Erro de sintaxe ocorre quando executamos uma sentença inválida. Veja o exemplo abaixo.

In [1]:
if 3 > 1
    print("True")
else
    print("False")

SyntaxError: invalid syntax (<ipython-input-1-03ff5076eab3>, line 1)

### Erros Runtime

In [2]:
# Divisão por zero
a = 2
b = 0
a/b # Gera um erro em tempo de execução

ZeroDivisionError: division by zero

In [3]:
# Executar uma operação com tipos incompatíveis
10/"5" # Gera um erro em tempo de execução

TypeError: unsupported operand type(s) for /: 'int' and 'str'

In [4]:
# Acessar elementos de uma lista que não existem
c = [1, 2, 3]
print(c[3]) # Gera um erro em tempo de execução

IndexError: list index out of range

### Erros de Lógica

In [5]:
a = "10"
if a == 10:
    print("True")
else:
    print("False")
        

False


### Tupla
#### Uma sequência de elementos ordenada e imutável

In [6]:
# Uma tupla é iterável
tup = (True, "banana", 2, None)
for x in tup:
    print(x)

True
banana
2
None


In [7]:
# Uma tupla é imutável
tup[0] = "a"

TypeError: 'tuple' object does not support item assignment

### Set
#### É uma coleção não ordenada de objetos distintos útil para testar pertinência a grupos, e fazer operações como intersecção e união

In [8]:
c1 = {1, 2, 3, 4}
c2 = {3, 4, 5, 6}

#### Verificação de pertinência de elemento a grupo

In [9]:
print(1 in c1)
print(9 in c2)

True
False


#### União de conjuntos

In [10]:
print(c1 | c2)

{1, 2, 3, 4, 5, 6}


#### Intersecção entre conjuntos

In [11]:
print(c1 & c2)

{3, 4}


### Função zip

In [12]:
letras = ["a", "b", "c"]
numeros = [1, 2, 3]

for l, n in zip(letras, numeros):
    print(f'{l}, {n}')

a, 1
b, 2
c, 3


### Instruções inline e List Comprehension

In [13]:
# 1) Escreva uma instrução if else na forma inline
# Dica - Sintaxe: valor_se_verdadeiro if condicao else valor_se_falso
# 2) Escreva uma instrução de loop (for) na forma inline calculando [1, 4, 9 ... 100]
# Dica - Sintaxe: [ OPERACAO_VAL for VAL in SEQUENCIA ]

a = 2
# Sintaxe: valor_se_verdadeiro if condicao else valor_se_falso
b = 0 if a > 10 else 1  #Sintaxe: vv if cond else vf
print(b)
# [ OPERACAO_VAL for VAL in SEQUENCIA ]
resultado1 = [x for x in range(10)] # list comprehension
resultado2 = [x * x for x in range(10)]
print(resultado1)
print(resultado2)

1
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


## NumPy Arrays


In [14]:
import numpy as np

### Criando ndarrays

In [15]:
# 1) Crie um array unidimensional a partir da lista [6, 7.5, 8, 0, 1]
# 2) Crie um array bidimensional a partir da lista [[1, 2, 3, 4], [5, 6, 7, 8]]
# 3) Crie um array unidimensional de zeros

data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
print(arr1)
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)
print(np.zeros(5)) # Função que cria um array de zeros

[6.  7.5 8.  0.  1. ]
[[1 2 3 4]
 [5 6 7 8]]
[0. 0. 0. 0. 0.]


In [16]:
# 1) Crie o seguinte array arr1 = np.array([6, 7.5, 8, 0, 1])
# 2) Imprima o tipo do dado do array arr1
# 3) Crie o seguinte array arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=np.int32)
# 4) Imprima o shape e o número de dimensões do array arr2

# O tipo do dado é inferido. Mas também pode ser especificado
arr1 = np.array([6, 7.5, 8, 0, 1])
print(arr1.dtype) # tipo do dado
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=np.int32)
print(arr2.shape) # Forma/dimensões do array
print(arr2.ndim) # Quantidade de dimensões

float64
(2, 4)
2


### Conversão de tipos (cast)

In [17]:
# 1) Crie o seguinte array num_str = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
# 2) Converta-o para o tipo float
# 3) Crie o seguinte array arr1 = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
# 4) Converta-o para o tipo int32

num_str = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
arr_float = num_str.astype(float) # Converte para float
print(arr_float)
arr1 = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr1_int = arr1.astype(np.int32) # Converte para int32
print(arr1_int)

[ 1.25 -9.6  42.  ]
[ 3 -1 -2  0 12 10]


### Operações vetorizadas em ndarrays
#### Mais eficientes (preferíveis)

In [18]:
# 1) Importe a biblioteca numpy e lhe dê o apelido np 
# 2) Crie um array (data) bidimensional de 2 linhas e 3 colunas de números aleatórios
# 3) Multiplique todos os elementos do vetor por 10
# 4) Some os elementos do array data a ele mesmo

import numpy as np # Importa a biblioteca numpy e lhe dá o apelido de np 
data = np.random.randn(2, 3) # Gerar dados aleatórios. 2L x 3C
print(data)
print(data * 10)
print(data + data)

[[ 0.2134361   0.64271684  2.13394185]
 [-0.3614577  -1.1876562  -0.84676889]]
[[  2.13436096   6.42716844  21.33941847]
 [ -3.61457701 -11.87656203  -8.46768891]]
[[ 0.42687219  1.28543369  4.26788369]
 [-0.7229154  -2.37531241 -1.69353778]]


### Aritmética com NumPy Arrays

In [19]:
# 1) Crie os seguintes arrays arr = np.array([1., 2., 3.]) e arr2 = np.array([4., 5., 6.])
# 2) Calcule arr * arr
# 3) Calcule arr - arr
# 4) Calcule 1 / arr
# 5) Calcule a raiz quadrada dos elementos de arr
# 6) Calcule arr - arr
# 7) Compare os elementos do array arr com os elementos do arr2

arr = np.array([1., 2., 3.])
arr2 = np.array([4., 5., 6.])
print(arr * arr)
print(arr - arr)
print(1 / arr)
print(arr ** 0.5)
print(arr2 > arr)

[1. 4. 9.]
[0. 0. 0.]
[1.         0.5        0.33333333]
[1.         1.41421356 1.73205081]
[ True  True  True]


### Comparação de Desempenho: Numpy array vs list

In [20]:
# 1) Crie um numpy array com 10 milhoes de numeros sequenciais
# 2) Crie uma lista 10 milhoes de numeros sequenciais
# 3) Meça o tempo de multiplicar todos os elementos do array por 2
# 4) Meça o tempo de multiplicar todos os elementos da lista por 2
# Dica: %time mede o tempo tomado pela execução da linha
# Dica: Não precisa importar a biblioteca numpy novamente. 
#       Ela foi importada na célula 19, acima.

my_arr = np.arange(10000000) # Função que cria um array de números sequenciais
my_list = list(range(10000000))
# %time mede o tempo tomado pela execução da linha
%time my_arr2 = my_arr * 2
%time my_list2 = [x * 2 for x in my_list]
print(my_arr2[1:5])
print(my_list2[1:5])

CPU times: user 9.49 ms, sys: 13.7 ms, total: 23.2 ms
Wall time: 23.2 ms
CPU times: user 375 ms, sys: 147 ms, total: 522 ms
Wall time: 521 ms
[2 4 6 8]
[2, 4, 6, 8]


### Slicing (fatiar) NumPy Arrays
#### Nas listas os slices são cópias
#### Nos arrays numpy os slices são views (visualizações)

In [21]:
# 1) Crie o seguinte array: arr = np.arange(10)
# 2) Guarde na variavel arr_slice os elementos de índice 5 até 8 deste array
# 3) Atribua o valor 12345 ao elemento de índice 1 do array arr_slice
# 4) Visualize o arr e perceba que o elemento de índice 6 alterou de valor
# 5) Crie a seguinte lista: li2 = list(range(10))
# 6) Guarde na variavel list_slice os elementos de índice 5 até 8 da lista li2
# 7) Atribua o valor 12345 ao elemento de índice 1 da lista list_slice
# 8) Visualize a lista li2 e perceba que o elemento de índice 6 alterou de valor

arr = np.arange(10)
print(arr)
arr_slice = arr[5:8]
arr_slice[1] = 12345
print(arr)
li2 = list(range(10)) # Repetindo a operação equivalente com uma lista
list_slice = li2[5:8]
list_slice[1] = 12345
print(li2)

[0 1 2 3 4 5 6 7 8 9]
[    0     1     2     3     4     5 12345     7     8     9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


### Slicing (fatiar) de arrays bidimensionais

In [22]:
# 1) Crie o seguinte array bidimensional: arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# 2) Imprima o shape desse array
# 3) Imprima a linha de índice 2 desse array
# 4) Imprima o elemento de posição 0,2 desse array, usando as sintaxes com e sem vírgula

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d.shape)
print(arr2d[2])
print(arr2d[0][2]) # Tanto faz
print(arr2d[0, 2]) # Tanto faz

(3, 3)
[7 8 9]
3
3


### Outras funções numpy

### Função Soma (np.sum)

In [23]:
ar = np.array([[0, 1], [0, 5]])
print(ar)
print(np.sum(ar))
print(np.sum(ar, axis=0))
print(np.sum(ar, axis=1))

[[0 1]
 [0 5]]
6
[0 6]
[1 5]


### Função média (np.mean)

In [24]:
ar = np.array([[2, 1], [0, 5]])
print(ar)
print(np.mean(ar))
print(np.mean(ar, axis=0))
print(np.mean(ar, axis=1))

[[2 1]
 [0 5]]
2.0
[1. 3.]
[1.5 2.5]


### Função desvio padrão (np.std)

In [25]:
ar = np.array([[2, 1], [0, 5]])
print(ar)
print(np.std(ar))
print(np.std(ar, axis=0))
print(np.std(ar, axis=1))

[[2 1]
 [0 5]]
1.8708286933869707
[1. 2.]
[0.5 2.5]


### Função algum (np.any)

In [26]:
arr2 = np.array([[True, False], [True, True]])
print(arr2)
print(np.any(arr2))
print(np.any(arr2, axis=0))

[[ True False]
 [ True  True]]
True
[ True  True]


### Função np.argmax

In [27]:
a = np.array([[10, 11, 12],
          [13, 14, 15]])
print(a)
print(np.argmax(a))
print(np.argmax(a, axis=0))
print(np.argmax(a, axis=1))

[[10 11 12]
 [13 14 15]]
5
[1 1 1]
[2 2]


### Filtrar um Array baseado numa condição

In [28]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
print(arr)
print(arr < 4)
print(arr[arr < 4])

[0 1 2 3 4 5 6 7 8]
[ True  True  True  True False False False False False]
[0 1 2 3]


### Operações lógicas com Array Numpy

In [29]:
arr1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
selecao = (arr1 > 2) & (arr1 <5)
print(selecao)
print(arr1[selecao])

[False False False  True  True False False False False]
[3 4]


In [30]:
selecao2 = (arr1 < 2) | (arr1 > 5)
print(selecao2)
print(arr1[selecao2])

[ True  True False False False False  True  True  True]
[0 1 6 7 8]
